-- Execute uma vez em cada banco Supabase de empresa antes de publicar a API.
CREATE TABLE IF NOT EXISTS app.mensagem_conversa
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id BIGINT NOT NULL,
    remetente_id BIGINT NOT NULL REFERENCES app.usuario(id),
    destinatario_id BIGINT NOT NULL REFERENCES app.usuario(id),
    texto TEXT NOT NULL DEFAULT '',
    foto BYTEA NULL,
    foto_nome TEXT NULL,
    foto_tipo TEXT NULL,
    enviada_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    lida_em TIMESTAMPTZ NULL,
    CONSTRAINT ck_mensagem_conversa_pares_diferentes CHECK (remetente_id <> destinatario_id),
    CONSTRAINT ck_mensagem_conversa_conteudo CHECK (length(texto) > 0 OR foto IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS ix_mensagem_conversa_destinatario_nao_lida
    ON app.mensagem_conversa (empresa_id, destinatario_id, remetente_id, enviada_em DESC)
    WHERE lida_em IS NULL;

CREATE INDEX IF NOT EXISTS ix_mensagem_conversa_par_data
    ON app.mensagem_conversa (empresa_id, remetente_id, destinatario_id, enviada_em, id);
