-- Execute uma vez no Supabase separado usado como catálogo central da plataforma.
CREATE SCHEMA IF NOT EXISTS platform;

CREATE TABLE IF NOT EXISTS platform.empresa_catalogo
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    nome TEXT NOT NULL,
    email_responsavel TEXT NOT NULL,
    conexao_criptografada BYTEA NOT NULL,
    status TEXT NOT NULL DEFAULT 'PENDENTE',
    ativa BOOLEAN NOT NULL DEFAULT FALSE,
    criada_por TEXT NOT NULL,
    aprovada_por TEXT NULL,
    aprovada_em TIMESTAMPTZ NULL,
    criada_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_empresa_catalogo_nome
    ON platform.empresa_catalogo (LOWER(nome));

REVOKE ALL ON SCHEMA platform FROM PUBLIC, anon, authenticated;
REVOKE ALL ON ALL TABLES IN SCHEMA platform FROM PUBLIC, anon, authenticated;
