-- Reinicializa o chat de prototipo no banco central.
-- Execute no Supabase configurado como ConnectionStrings:CadastroCentral.
-- Remove somente o schema chat; o catalogo platform e os bancos das empresas nao sao tocados.
-- O acesso continua passando pela API, que valida sessao, aparelho e empresa.

DROP SCHEMA IF EXISTS chat CASCADE;
CREATE SCHEMA IF NOT EXISTS chat;

CREATE TABLE chat.configuracao
(
    id BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK (id=TRUE),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO chat.configuracao (id,ativo) VALUES (TRUE,TRUE);

CREATE TABLE IF NOT EXISTS chat.conversa
(
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    empresa_id BIGINT NOT NULL,
    tipo TEXT NOT NULL DEFAULT 'DIRETA',
    usuario_menor_id BIGINT NULL,
    usuario_maior_id BIGINT NULL,
    criada_por_usuario_id BIGINT NOT NULL,
    criada_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    atualizada_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_chat_conversa PRIMARY KEY (empresa_id, id),
    CONSTRAINT ck_chat_conversa_tipo CHECK (tipo IN ('DIRETA', 'GRUPO')),
    CONSTRAINT ck_chat_conversa_empresa CHECK (empresa_id > 0),
    CONSTRAINT ck_chat_conversa_direta CHECK
    (
        (tipo = 'DIRETA' AND usuario_menor_id IS NOT NULL AND usuario_maior_id IS NOT NULL
         AND usuario_menor_id > 0 AND usuario_menor_id < usuario_maior_id)
        OR (tipo = 'GRUPO' AND usuario_menor_id IS NULL AND usuario_maior_id IS NULL)
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_chat_conversa_direta_empresa_usuarios
    ON chat.conversa (empresa_id, usuario_menor_id, usuario_maior_id)
    WHERE tipo = 'DIRETA';

CREATE TABLE IF NOT EXISTS chat.participante
(
    empresa_id BIGINT NOT NULL,
    conversa_id UUID NOT NULL,
    usuario_id BIGINT NOT NULL,
    entrou_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    saiu_em TIMESTAMPTZ NULL,
    ultima_leitura_em TIMESTAMPTZ NULL,
    CONSTRAINT pk_chat_participante PRIMARY KEY (empresa_id, conversa_id, usuario_id),
    CONSTRAINT ck_chat_participante_ids CHECK (empresa_id > 0 AND usuario_id > 0),
    CONSTRAINT fk_chat_participante_conversa
        FOREIGN KEY (empresa_id, conversa_id)
        REFERENCES chat.conversa (empresa_id, id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_chat_participante_usuario
    ON chat.participante (empresa_id, usuario_id, conversa_id)
    WHERE saiu_em IS NULL;

CREATE TABLE IF NOT EXISTS chat.mensagem
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id BIGINT NOT NULL,
    conversa_id UUID NOT NULL,
    remetente_id BIGINT NOT NULL,
    cliente_mensagem_id UUID NULL,
    origem_mensagem_legada_id BIGINT NULL,
    remetente_nome TEXT NOT NULL DEFAULT '',
    destinatario_nome TEXT NOT NULL DEFAULT '',
    texto TEXT NOT NULL DEFAULT '',
    foto BYTEA NULL,
    foto_nome TEXT NULL,
    foto_tipo TEXT NULL,
    enviada_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    atualizada_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    editada_em TIMESTAMPTZ NULL,
    excluida_em TIMESTAMPTZ NULL,
    versao INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT uq_chat_mensagem_empresa_id UNIQUE (empresa_id, id),
    CONSTRAINT fk_chat_mensagem_conversa
        FOREIGN KEY (empresa_id, conversa_id)
        REFERENCES chat.conversa (empresa_id, id) ON DELETE CASCADE,
    CONSTRAINT fk_chat_mensagem_remetente
        FOREIGN KEY (empresa_id, conversa_id, remetente_id)
        REFERENCES chat.participante (empresa_id, conversa_id, usuario_id),
    CONSTRAINT ck_chat_mensagem_conteudo CHECK (length(texto) > 0 OR foto IS NOT NULL),
    CONSTRAINT ck_chat_mensagem_versao CHECK (versao > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_chat_mensagem_cliente_id
    ON chat.mensagem (empresa_id, remetente_id, cliente_mensagem_id)
    WHERE cliente_mensagem_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_chat_mensagem_origem_legada
    ON chat.mensagem (empresa_id, origem_mensagem_legada_id)
    WHERE origem_mensagem_legada_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_chat_mensagem_conversa_data
    ON chat.mensagem (empresa_id, conversa_id, enviada_em DESC, id DESC);

CREATE TABLE IF NOT EXISTS chat.recibo_mensagem
(
    empresa_id BIGINT NOT NULL,
    mensagem_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    entregue_em TIMESTAMPTZ NULL,
    lida_em TIMESTAMPTZ NULL,
    CONSTRAINT pk_chat_recibo_mensagem PRIMARY KEY (empresa_id, mensagem_id, usuario_id),
    CONSTRAINT fk_chat_recibo_mensagem_mensagem
        FOREIGN KEY (empresa_id, mensagem_id)
        REFERENCES chat.mensagem (empresa_id, id) ON DELETE CASCADE,
    CONSTRAINT ck_chat_recibo_usuario CHECK (usuario_id > 0)
);

CREATE TABLE IF NOT EXISTS chat.reacao_mensagem
(
    empresa_id BIGINT NOT NULL,
    mensagem_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    emoji TEXT NOT NULL,
    criada_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_chat_reacao_mensagem PRIMARY KEY (empresa_id, mensagem_id, usuario_id, emoji),
    CONSTRAINT fk_chat_reacao_mensagem_mensagem
        FOREIGN KEY (empresa_id, mensagem_id)
        REFERENCES chat.mensagem (empresa_id, id) ON DELETE CASCADE,
    CONSTRAINT ck_chat_reacao_emoji CHECK (length(emoji) BETWEEN 1 AND 32),
    CONSTRAINT ck_chat_reacao_usuario CHECK (usuario_id > 0)
);

-- Apelidos permanecem privados por empresa e por usuário, mesmo no banco comum.
CREATE TABLE IF NOT EXISTS chat.usuario_apelido
(
    empresa_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    contato_id BIGINT NOT NULL,
    apelido TEXT NOT NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_chat_usuario_apelido PRIMARY KEY (empresa_id, usuario_id, contato_id),
    CONSTRAINT ck_chat_usuario_apelido_usuarios CHECK
        (empresa_id > 0 AND usuario_id > 0 AND contato_id > 0 AND usuario_id <> contato_id),
    CONSTRAINT ck_chat_usuario_apelido_texto CHECK (length(trim(apelido)) BETWEEN 1 AND 60)
);

CREATE INDEX IF NOT EXISTS ix_chat_mensagem_empresa_data
    ON chat.mensagem (empresa_id, enviada_em DESC, id DESC);

REVOKE ALL ON SCHEMA chat FROM PUBLIC, anon, authenticated;
REVOKE ALL ON ALL TABLES IN SCHEMA chat FROM PUBLIC, anon, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA chat FROM PUBLIC, anon, authenticated;
